### ISSUE TITLE
Scans

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#1]
Did you have/find scans for these stories? I thought I saw you refer to them a couple of times on the list. If so, they should be in dc:source tags in `content.opf`, and listed in the `colophon` and `imprint`.

Also, a question for @acabal. Alex, when Robin reviewed O. Henry, he had me put the links to _all_ the transcriptions and scans in the `colophon`. I'd never done that before, but it looked good. Do we want to do that here as well, i.e. is that what we should always do when there are multiple transcriptions/scans involved? I couldn't find anything in the manual about the `colophon`, so I wanted to check. The `imprint` still only had the first one.

**Comment by davebytemfg** [comment]
@vr8hub yes I have scans for everything but pipe-dream, I checked several of the other short story collections and couldn't find them listing all the scans in those, but I didn't do an exhaustive search through the repo.

But yes, I have the links and simple to add them where ever we need. I'll add the dc:source now.

The colophon and imprint would get long with the 25 links? If there's a sample format, happy to follow it depending on how Alex responds.

**Comment by davebytemfg** [comment]
Added scan dc:sources in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

waiting for feedback on colophon and imprint.

**Comment by vr8hub** [comment]
While we're waiting, you can look at O. Henry to see how they're formatted in the colophon. We still didn't put them all in the imprint, just the colophon.

Yes, you have even more links than I did (I had 14-15 each for transcriptions and scans, if I recall correctly), that's why I'm checking with Alex.

**Comment by acabal** [comment]
We don't have a colophon formula yet for when multiple scans are involved. It's kind of ad-hoc. I'd be interested in hearing proposals to standardize it.

In this case I think it would be pretty tedious to list all 25 transcriptions. Certainly tedious in the imprint which is meant to be a shortish intro block and not a full credits. If we're going to think of a standard for this, I think length is something to consider. Maybe it's OK to list all sources if there's say < 3-4, but any more than that and we just list the name of the source without a link?

So in this case, I would be OK with just using the first dc:source in the metadata as the link of choice for the imprint/colophon, and leave it at that.ifi

**Comment by davebytemfg** [comment]
For the PG link, we could link to the author page since (at least right now) this book covers everything but one book?

https://www.gutenberg.org/ebooks/author/25421

Or just link it to the first story in the book / dc:source? Would that be better? Either way, let me know!

@acabal @vr8hub

**Comment by vr8hub** [comment]
Historically, we have linked to the first one in the `dc:source`; I'll let Alex answer if he wants to make an exception for that.

**Comment by davebytemfg** [comment]
No worries, I'll link to the first story. Simple enough!

**Comment by davebytemfg** [comment]
Fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

**Comment by acabal** [comment]
Let's use the first dc:source. Listing the author won't work for most cases because many authors wrote short stories along with longer standalone works.
