### ISSUE TITLE
Teletype

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#10]
This one I'm going to get @acabal to weigh in on.

Alex, In "[The 64-Square Madhouse](https://github.com/davebytemfg/fritz-leiber_short-fiction/blob/master/src/epub/text/the-64-square-madhouse.xhtml)", there are multiple instances where a machine communicates to others on an electric board. The computer uses all (small) caps to communicate. Since they're random paragraphs, Dave used a class ("teletype").

A `<b>` could be used here instead, but then it would not be _all_ small caps, and since the paragraphs are random throughout, there's not really any other selectors that I see that could be used to target the `<b>`.
Is using a class OK in this instance, or do you think small caps is close enough?
(I think this is a good use of a class, but I'm almost always wrong when I think that. :)

**Comment by acabal** [comment]
Yes, I think this is a good use of a class.
