### ISSUE TITLE
Lint ignore

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#11]
The only lint message that should be ignored is the one for Alice O. All of the others should be corrected per lint's instructions.

**Comment by davebytemfg** [comment]
fixed on branch https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-lint-1

**Comment by davebytemfg** [comment]
The nice-girl-with-5-husbands.xhtml ignores are triggering on the MathML code, we spend a bunch of time on that on the mailing list, and Alex is fixing some other tool build issue with it as well. I think it's right to suppress those, unless Alex can give some additional guidance on how to structure the MathML properly. I'm not an expert on that.

**Comment by vr8hub** [comment]
No, you're exactly right, I forgot about those, that's my mistake.
