### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#2]
You have a few blockquotes with an epub:type of z3998:newspaper. I can't find "newspaper" anywhere in the z3998 vocabulary; where did you find that?

**Comment by davebytemfg** [comment]
@vr8hub Good catch, I copied it from:

https://github.com/standardebooks/christopher-morley_the-haunted-bookshop/blob/master/src/epub/text/chapter-4.xhtml

I must not have checked https://www.daisy.org/z3998/2012/vocab/structure/

What's the right way to format newspaper headlines and such, I think mostly I was trying reuse the CSS from christopher-morley_the-haunted-bookshop to display the newspaper like layout in pipe-dream and yesterday-house.

Can you point me to something else more appropriate, if that's not right?

**Comment by vr8hub** [comment]
Interesting. I’ll submit a PR to fix it.

Just a plain `blockquote` (no semantics) with a `<header>`.
