### ISSUE TITLE
Chapter h# numbers

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#4]
Each "level" in the book increases the `h#`. Since the stories themselves are `h2`, then the chapters within the stories should be `h3`.

**Comment by davebytemfg** [comment]
Good catch! Wonder if lint could be taught to see those as well.

fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

**Comment by vr8hub** [comment]
I would think it would be pretty difficult, but PR’s are always welcome. :)
