### ISSUE TITLE
Verse vs poem

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#6]
This isn't explicitly laid out in the manual, at least last I looked, but the difference between z3998:verse and z3998:poem is the latter is when an entire poem is quote, and the former is for a portion of a poem. There are a few places in here where portions are quote that are marked as `z3998:poem`; they should be `z3998:verse` instead.

**Comment by davebytemfg** [comment]
fixed in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes
