### ISSUE TITLE
Abbreviations

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#7]
There are a number of abbreviations throughout the book that are not marked with the proper class, e.g. USSR, MA, etc. See [section 8.10](https://standardebooks.org/manual/1.0.0/8-typography#8.10) in the manual for the specifics.

Also, there are abbreviations in at least one of the epigraphs that aren't marked, e.g. `Ch.`.

**Comment by davebytemfg** [comment]
@vr8hub

	+ the-night-of-the-long-knives.xhtml
				<p>“Bentleys and Porsches!”</p>
				<p>“Aircoups and <abbr class="initialism">D.C.4.</abbr>s and Comets!”</p>
				<p>“Martinis and hashish and ice cream sodas!”</p>
		se lint doesn't handle a number properly, throws a t-030 - Initialism with spaces or without periods.
			works fine with D.C. or DC4 without the initialism
	leave the initialization class off or add it to the ignore file, or change it and let lint fail until someone updates lint?? (or something else?)

**Comment by davebytemfg** [comment]
@vr8hub when you get a chance, take a look at the diff between these two branches
https://github.com/davebytemfg/fritz-leiber_short-fiction/compare/ddk-feedback-fixes...ddk-abbr-changes

Maybe I was too aggressive with the additions of the class="initialism" and the dots?

Please let me know what you think!

ESP / 3D in particular seems odd to put dots in, but did it anway. I left the DC4 out until you have a chance to review the earlier comment.

**Comment by vr8hub** [comment]
I didn't look at every single one, but overall it looks good. These stories had a lot of abbreviations. :) I did see an "MA", but I wasn't sure from the context what it was referring to. If it's referring to the state, then that has a different class ("postal"); it would be a good idea to (re?)review the entire section on abbreviations in the manual. (I still have to do it regularly.) There are a lot of kinds of abbreviations, and the manual does a pretty good job of distinguishing them.

DC4 is a good question. Lint doesn't complain if it's a plain abbreviation without periods, but it does if the D.C. has periods (the 4 definitely shouldn't have one), with or without a class.

The ESP / 3D should be treated as two separate abbreviations; the ESP would be an initialism, while the 3D is in the same boat as the DC4.

I'll ask on the list about the DC4/3D; it will be helpful to have it in the list archives.

**Comment by davebytemfg** [comment]
Ok, sounds good. I did fix up the MA one, stood for 'Murderers Anonymous' a play on AA.
