### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by vr8hub** [davebytemfg/fritz-leiber_short-fiction#8]
1. There's an "Ms" in Creature from Cleveland Depths that semanticate wants to markup as an abbreviation. I think there should be an apostrophe there, i.e. M's.
2. There's an organization name with italics in at least one place (64 Square?). Per [here](https://standardebooks.org/manual/1.0.0/8-typography#8.2.8.2) in the manual, proper names aren't italicized. Be sure to check if there are others.
3. There are a couple of places where author names are italicized as a book. We only italicize the actual book name, not the author, even when the author name is being used a stand-in for the book title.
4. There are roman semantics on some non-roman characters, e.g. a reference to a `V` cut by a boat in Yesterday House. Semanticate can only so smart, so be sure and check all of your z3998:roman tags to make sure they're actually roman characters.
5. In 64 Square, there's a reference to MCO and the book name, separated by a simple dash. That should probably be an em-dash; a few sentences later, it refers to another book (the "New Testament"), and it does use an em-dash there.
6. There are several foreign phrases that appear in Merriam-Webster; they should not be italicized or have language semantics. (See [here](https://standardebooks.org/manual/1.0.0/8-typography#8.2.8.4).)

**Comment by davebytemfg** [comment]
@vr8hub  to confirm on all of these, I can ignore the actual formatting in the scans and do what the SE manual says with regard to the things you've pointed out?

**Comment by davebytemfg** [comment]
Fixes for 1, 4 and 5 in https://github.com/davebytemfg/fritz-leiber_short-fiction/tree/ddk-feedback-fixes

**Comment by vr8hub** [comment]
If the manual has explicit instructions, then yes. For example, books italicize a lot of foreign phrases that we don't, because they appear in M-W. Since the manual has explicit instructions for those, we remove the italics. And so on.

**Comment by davebytemfg** [comment]
@vr8hub for #3 above, I've reviewed all the epub:type="se:name.publication.book" references and I'm not seeing it.

Maybe you mean the epigraph / cite in the the-night-of-the-long-knives?? Can you point out a specific instance and I'll dig some more!

**Comment by davebytemfg** [comment]
@vr8hub for #6, the scan has all three of these as a single italics, the first two are in m-w, the last one isn't, sooo leave the whole thing in italics?? I'm assuming this is some quote from some play or something, but I can't find it with google.

				<p>Martin stood tall, spread his arms rather like a high priest, and intoned, “<i xml:lang="la">Amici! Romani! Populares!</i>”</p>

**Comment by vr8hub** [comment]
For #3, I mistook a word for an author's name, which it apparently isn't, so my bad. But the issue is the same.
In 64 Square, both "Archives" and "Shakhmaty" are italicized with book semantics.
There are lots of things "Archives" could be referring to (I don't see it referenced anywhere else in the story), including books and magazines. Whatever it is, it's almost certain "Archives" isn't its full name.
I'm guessing Shakhmaty (which I initially took for an author's name) is referring to "[Shakhmaty v SSSR](https://en.wikipedia.org/wiki/Shakhmaty_v_SSSR)," which is a magazine, not a book. But, since it's abbreviated here, it wouldn't be italicized.

Yes, phrases are italicized if the entire phrase isn't known, i.e. in M-W.
